{% set version = "2.5.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dalex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DALEX_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DALEX/DALEX_{{ version }}.tar.gz
  sha256: 1eea482799302964cb3d2689e66e3071c2ffc30d3e1ae151f476f8daa0932726

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-ibreakdown >=1.3.1
    - r-ingredients >=2.0
    - r-kernelshap
  run:
    - r-base
    - r-ggplot2
    - r-ibreakdown >=1.3.1
    - r-ingredients >=2.0
    - r-kernelshap

test:
  commands:
    - $R -e "library('DALEX')"           # [not win]
    - "\"%R%\" -e \"library('DALEX')\""  # [win]

about:
  home: https://ModelOriented.github.io/DALEX/, https://github.com/ModelOriented/DALEX
  license: GPL-2.0-or-later
  summary: Unverified black box model is the path to the failure. Opaqueness leads to distrust. Distrust leads to ignoration. Ignoration leads to rejection. DALEX package xrays any model and helps to explore and explain its behaviour. Machine Learning (ML) models are widely used and have various applications in classification
    or regression. Models created with boosting, bagging, stacking or similar techniques are often used due to their high performance. But such black-box models usually lack of direct interpretability. DALEX package contains various methods that help to understand the link between input variables and model output. Implemented
    methods help to explore model on the level of a single instance as well as a level of the whole dataset. All model explainers are model agnostic and can be compared across different models. DALEX package is the cornerstone for 'DrWhy.AI' universe of packages for visual model exploration. Find more details in (Biecek
    2018) <arXiv:1806.08915>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: DALEX
# Title: moDel Agnostic Language for Exploration and eXplanation
# Version: 1.2.0
# Authors@R: c(person("Przemyslaw", "Biecek", email = "przemyslaw.biecek@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-8423-1823")), person("Szymon", "Maksymiuk", role = "aut"), person("Hubert", "Baniecki", role = "aut", comment = c(ORCID = "0000-0001-6661-5364")))
# Description: Unverified black box model is the path to the failure. Opaqueness leads to distrust. Distrust leads to ignoration. Ignoration leads to rejection. DALEX package xrays any model and helps to explore and explain its behaviour. Machine Learning (ML) models are widely used and have various applications in classification or regression. Models created with boosting, bagging, stacking or similar techniques are often used due to their high performance. But such black-box models usually lack of direct interpretability. DALEX package contains various methods that help to understand the link between input variables and model output. Implemented methods help to explore model on the level of a single instance as well as a level of the whole dataset. All model explainers are model agnostic and can be compared across different models. DALEX package is the cornerstone for 'DrWhy.AI' universe of packages for visual model exploration. Find more details in (Biecek 2018) <arXiv:1806.08915>.
# License: GPL
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# Depends: R (>= 3.5)
# Imports: ggplot2, iBreakDown, ingredients
# Suggests: gower, ggpubr, ranger, testthat
# URL: https://ModelOriented.github.io/DALEX/, https://github.com/ModelOriented/DALEX
# BugReports: https://github.com/ModelOriented/DALEX/issues
# NeedsCompilation: no
# Packaged: 2020-04-22 19:45:26 UTC; pbiecek
# Author: Przemyslaw Biecek [aut, cre] (<https://orcid.org/0000-0001-8423-1823>), Szymon Maksymiuk [aut], Hubert Baniecki [aut] (<https://orcid.org/0000-0001-6661-5364>)
# Maintainer: Przemyslaw Biecek <przemyslaw.biecek@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-04-22 20:34:10 UTC
