travis:
  secure:
    BINSTAR_TOKEN: Dp7e/hzntD12alRMzWT8Bxtw9WmwUTsOzpuUA2iv7Asre3Fzv7gwFK59pwHw3WM7BHVIlAKjjtnESkN5JaSI6nWysquB+1p/YEmHh89eLE4YGvxTOKjK8MNjzWSen/D6mFVVaqYmDtna6o/Qk6N/Klgkrf+LS+bKLn0vN3AsOyW5SR6BUpVjZyWFp3nRbWFvwliDtyI33SvjMM1Dm4BsWaiS/JErP3lCa0lZ8Jf23pvyfGwTz82vu8X7z64RFI3vN3OQg7vZ9sUZLMSqpO7CL7kllK92U72fVnKpuXo0/W3qYJJGLbHlwtzXhU5lY3dpnp/2v2TJVApIHFGo/4du0vyogLgjyjD0IfTLvujbOXrU6x+3iXqP1bKDi2GStzPGNOUphzgXSnEQ8pijRW5uTVdAmrEiOaRqCwaFLQSDWqS3dr2DsrdrYEizFxXhBQcZ9HIhJZx+zPLQXBRFsadDhduJ4mRrCOO0DjAezuqOd6yBeJnJkJ/F+c3rCgKhR/Nt3NF/MvZ/uMd52GJk6remlLgMyqQjSru9N6dkDPQFKjuIISpfP1ixv9qfPs4LBXhC7q5MmSO1XzIO8wsng8oz9ve/snvl0BHZuzTim6V2GErkjcSkhl2pXJz0hGnIOJ3LR3a8rxh8BCMUI2i62hB5G2jLKrpz8IhWRr48sjSi+OU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
