travis:
  secure:
    BINSTAR_TOKEN: OekvjADyTmycTRnbjLcz/DEkUfkfoXYJhAYPlDqtVcRODvHHk5CY4k4pO02EqkTgY9xNBnkytS6ZIkV0nxKUZuf8hDSRCNFyPIDYfsZI1oD7/AKpZge+YputylYGvGoRF1bqQTNdCQhFTLfSDAfOffdoeHE+jeIB8yeSPwspL8xqWEtGZWY4tnXQkS+ZMpQEumGYrwyP4ZO8+xiscBVzl3aNJXDfheqG5xcVkdzNd4J3YuuJE/NMuC3yM5zgjNtnScPlhFBHRnQR2xjjYEgdJyQw5RZxZF0EWcH9Mq3e4BV5YbQdWVznyO6mbWAG17HvJ6b2tsqtu8BWj0WX+H90hHfFhMm8Ih83GQ2+N6CnNl1xJk0rRrgw2mTNMNhfGSfNVtViDjymcK3AhzRm1eF6qxtP2Qdmvwt3QK4uZ6gTkvAAxB8JUe6n7NoP3SznOg9gt0nG2yq67w+L45xysVBTjvScO8eWhI7CBtBsIb5Kgc7ITIT1B3cRp8SGBWKg9kro0yFveIsBP1BZQ3nZjOQRD6R77Tmp9JOvlBsX2TZMsH6+tk7FlK41v8ANioKYdZpLJO80l/HY9V3/8ZBpiZkO5ohWYnCwvnHTgbEhVowREQ0u0psMGQwz+jcjpSMk11orT3PpF55ipqPbX9IzLA3bqOowVtu9U+EhLvEZB0h7uTo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
